// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdmymcefzmbckohzupgt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbXltY2Vmem1iY2tvaHp1cGd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NjA4NjYsImV4cCI6MjA3MjIzNjg2Nn0.X83vHjPN1bq_0MLYnauFo9r3NzGVUBG7fPjE4DN4DbM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});